<a href="https://colab.research.google.com/github/manisha-mishra-123/Scaler-projects/blob/main/ScalerMart_Business_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem Statement:
ScalerMart, a leading global electronics retailer, has experienced a significant downturn in sales, with a nearly 50% decline in revenue in 2020 compared to the previous year.

In response to this challenge, the company is actively seeking a sharp Data Analyst to join their growing team.

You have been assigned the task of analyzing the customer-level transactional data to identify potential reasons behind the decline in sales.

Your objective is to recommend data-driven strategies aimed at improving sales performance.

In [77]:
!gdown 1qPrP3QNWjxA_JHwao44dhVapEtQtlfus
!gdown 1fGc33yN_yTLI-1erTwo4-KdxFMcXDjJD
!gdown 1S0hQDcTlY3ZUpyD1gf50Cujfs8UTSgnt

Downloading...
From: https://drive.google.com/uc?id=1qPrP3QNWjxA_JHwao44dhVapEtQtlfus
To: /content/Customers.csv
100% 1.43M/1.43M [00:00<00:00, 76.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1fGc33yN_yTLI-1erTwo4-KdxFMcXDjJD
To: /content/Products.csv
100% 305k/305k [00:00<00:00, 83.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1S0hQDcTlY3ZUpyD1gf50Cujfs8UTSgnt
To: /content/Sales.csv
100% 2.80M/2.80M [00:00<00:00, 97.6MB/s]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [78]:
df_cus= pd.read_csv('Customers.csv', encoding='latin1')
df_cus

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965
...,...,...,...,...,...,...,...,...,...,...
15261,2099600,Female,Denisa Duková,Houston,TX,Texas,77017,United States,North America,3/25/1936
15262,2099618,Male,Justin Solórzano,Mclean,VA,Virginia,22101,United States,North America,2/16/1992
15263,2099758,Male,Svend Petrussen,Wilmington,NC,North Carolina,28405,United States,North America,11/9/1937
15264,2099862,Female,Lorenza Rush,Riverside,CA,California,92501,United States,North America,10/12/1937
15265,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965

In [79]:
df_prod= pd.read_csv('Products.csv')
df_prod

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio
...,...,...,...,...,...,...,...,...,...,...
2512,2513,Contoso Bluetooth Active Headphones L15 Red,Contoso,Red,$43.07,$129.99,505,Cell phones Accessories,5,Cell phones
2513,2514,Contoso Bluetooth Active Headphones L15 White,Contoso,White,$43.07,$129.99,505,Cell phones Accessories,5,Cell phones
2514,2515,Contoso In-Line Coupler E180 White,Contoso,White,$1.71,$3.35,505,Cell phones Accessories,5,Cell phones
2515,2516,Contoso In-Line Coupler E180 Black,Contoso,Black,$1.71,$3.35,505,Cell phones Accessories,5,Cell phones
2516,2517,Contoso In-Line Coupler E180 Silver,Contoso,Silver,$1.71,$3.35,505,Cell phones Accessories,5,Cell phones

In [80]:
df_sales= pd.read_csv('Sales.csv')
df_sales

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD
...,...,...,...,...,...,...,...,...,...
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

Customers Table Details

In [81]:
print('\nLength:\n ',len(df_cus))
print('\nSize:\n',df_cus.size)
print('\nShape:\n ',df_cus.shape)
print('\nData types:\n ',df_cus.dtypes)
print('\nDescription: \n',df_cus.describe())
print('\nUnique Values: \n')
for i in df_cus.columns:
  print(i,': ',df_cus[i].nunique())

Length:
  15266

Size:
 152660

Shape:
  (15266, 10)

Data types:
  CustomerKey     int64
Gender         object
Name           object
City           object
State Code     object
State          object
Zip Code       object
Country        object
Continent      object
Birthday       object
dtype: object

Description:
         CustomerKey
count  1.526600e+04
mean   1.060508e+06
std    6.127097e+05
min    3.010000e+02
25%    5.140335e+05
50%    1.079244e+06
75%    1.593980e+06
max    2.099937e+06

Unique Values:

CustomerKey :  15266
Gender :  2
Name :  15118
City :  8258
State Code :  467
State :  512
Zip Code :  9505
Country :  8
Continent :  3
Birthday :  11270

Product Table details

In [82]:
print('Length: ', len(df_prod))
print('\nShape: ', df_prod.shape)
print('\nSize: ', df_prod.size)
print('\nData types:\n ', df_prod.dtypes)
print('\nDescription:\n ', df_prod.describe())
print('\nUnique Values: \n')
for i in df_prod.columns:
  print(i,': ',df_prod[i].nunique())

Length:  2517

Shape:  (2517, 10)

Size:  25170

Data types:
  ProductKey         int64
Product Name      object
Brand             object
Color             object
Unit Cost USD     object
Unit Price USD    object
SubcategoryKey     int64
Subcategory       object
CategoryKey        int64
Category          object
dtype: object

Description:
          ProductKey  SubcategoryKey  CategoryKey
count  2517.000000     2517.000000  2517.000000
mean   1259.000000      491.810091     4.878824
std     726.739637      229.887134     2.299170
min       1.000000      101.000000     1.000000
25%     630.000000      305.000000     3.000000
50%    1259.000000      406.000000     4.000000
75%    1888.000000      801.000000     8.000000
max    2517.000000      808.000000     8.000000

Unique Values:

ProductKey :  2517
Product Name :  2517
Brand :  11
Color :  16
Unit Cost USD :  480
Unit Price USD :  426
SubcategoryKey :  32
Subcategory :  32
CategoryKey :  8
Category :  8

Sales Table Details

In [83]:
print('Length: ', len(df_sales))
print('\nShape: ', df_sales.shape)
print('\nSize: ', df_sales.size)
print('\nData types:\n ',df_sales.dtypes)
print('\nDescription:\n ', df_sales.describe())
print('\nUnique Values: \n')
for i in df_sales.columns:
  print(i,': ',df_sales[i].nunique())

Length:  62884

Shape:  (62884, 9)

Size:  565956

Data types:
  Order Number      int64
Line Item         int64
Order Date       object
Delivery Date    object
CustomerKey       int64
StoreKey          int64
ProductKey        int64
Quantity          int64
Currency Code    object
dtype: object

Description:
         Order Number     Line Item   CustomerKey      StoreKey    ProductKey  \
count  6.288400e+04  62884.000000  6.288400e+04  62884.000000  62884.000000
mean   1.430905e+06      2.164207  1.180797e+06     31.802144   1125.859344
std    4.532963e+05      1.365170  5.859634e+05     22.978188    709.244010
min    3.660000e+05      1.000000  3.010000e+02      0.000000      1.000000
25%    1.121017e+06      1.000000  6.808580e+05      8.000000    437.000000
50%    1.498016e+06      2.000000  1.261200e+06     37.000000   1358.000000
75%    1.788010e+06      3.000000  1.686496e+06     53.000000   1650.000000
max    2.243032e+06      7.000000  2.099937e+06     66.000000   2517.000000

           Quantity
count  62884.000000
mean       3.144790
std        2.256371
min        1.000000
25%        1.000000
50%        2.000000
75%        4.000000
max       10.000000

Unique Values:

Order Number :  26326
Line Item :  7
Order Date :  1641
Delivery Date :  1492
CustomerKey :  11887
StoreKey :  58
ProductKey :  2492
Quantity :  10
Currency Code :  5

In [84]:
for i in df_cus.columns:
  print(df_cus[i].value_counts())
  print('\n')

CustomerKey
301        1
1428088    1
1425887    1
1426096    1
1426124    1
          ..
696791     1
696874     1
696937     1
696960     1
2099937    1
Name: count, Length: 15266, dtype: int64


Gender
Male      7748
Female    7518
Name: count, dtype: int64


Name
John Smith           4
Robert Wilson        3
John Miller          3
Richard Smith        3
Mary Davis           3
                    ..
Arnaud Fluet         1
Paulette Chastain    1
Aceline Moïse        1
Constance Jobin      1
Zygmunt Kaminski     1
Name: count, Length: 15118, dtype: int64


City
Toronto              204
New York             130
Los Angeles          119
Montreal              97
Chicago               92
                    ...
Ronneburg              1
Gangkofen              1
Heßheim                1
Bremen Kattenesch      1
Lorton                 1
Name: count, Length: 8258, dtype: int64


State Code
CA                      740
ON                      644
IL                      597
TX                      522
NSW                     430
                       ...
Newcastle                 1
Basildon                  1
Reigate and Banstead      1
Barnet                    1
Christchurch              1
Name: count, Length: 467, dtype: int64


State
California             715
Ontario                644
Texas                  522
New South Wales        430
New York               423
                      ...
Nuneaton & Bedworth      1
Ely                      1
Brighton and Hove        1
Rossendale               1
North Warwickshire       1
Name: count, Length: 512, dtype: int64


Zip Code
90017      70
S4P 3Y2    50
H3C 5K4    37
48075      28
10016      27
           ..
1121 VW     1
3741 RA     1
6651 KT     1
9285 VR     1
28405       1
Name: count, Length: 9505, dtype: int64


Country
United States     6828
United Kingdom    1944
Canada            1553
Germany           1473
Australia         1420
Netherlands        733
France             670
Italy              645
Name: count, dtype: int64


Continent
North America    8381
Europe           5465
Australia        1420
Name: count, dtype: int64


Birthday
6/12/1989     5
7/3/1944      5
12/1/1964     5
10/12/1971    5
9/22/1951     5
             ..
8/28/1976     1
11/29/1962    1
9/8/1987      1
7/11/1965     1
8/18/1965     1
Name: count, Length: 11270, dtype: int64

In [85]:
print('\nNull values Customer Table: \n',df_cus.isnull().sum())

Null values Customer Table:
 CustomerKey     0
Gender          0
Name            0
City            0
State Code     10
State           0
Zip Code        0
Country         0
Continent       0
Birthday        0
dtype: int64

In [86]:
df_cus.loc[df_cus['State Code'].isnull(), ['State', 'State Code']]

       State State Code
5304  Napoli        NaN
5316  Napoli        NaN
5372  Napoli        NaN
5377  Napoli        NaN
5378  Napoli        NaN
5485  Napoli        NaN
5525  Napoli        NaN
5531  Napoli        NaN
5631  Napoli        NaN
5695  Napoli        NaN

In [87]:
df_cus['State Code'].fillna('NA', inplace= True)

In [88]:
for i in df_prod.columns:
  print(df_prod[i].value_counts(),'\n')

ProductKey
1       1
1683    1
1676    1
1677    1
1678    1
       ..
840     1
841     1
842     1
843     1
2517    1
Name: count, Length: 2517, dtype: int64

Product Name
Contoso 512MB MP3 Player E51 Silver                                       1
MGS Hand Games for 12-16 boys E600 Silver                                 1
MGS Hand Games women M400 Red                                             1
MGS Hand Games for 12-16 boys E600 Red                                    1
MGS Hand Games for Office worker L299 Red                                 1
                                                                         ..
Contoso Laptop Cooling Hub notebook fan with 4 ports USB hub M200 Gold    1
Contoso Reserve Pen - Tablet Pen E200 Gold                                1
Contoso Bright Light battery E20 Black                                    1
Contoso Bright Light battery E20 blue                                     1
Contoso In-Line Coupler E180 Silver                                       1
Name: count, Length: 2517, dtype: int64

Brand
Contoso                 710
Fabrikam                267
Litware                 264
Proseware               244
Adventure Works         192
Southridge Video        192
Wide World Importers    173
The Phone Company       152
Tailspin Toys           144
A. Datum                132
Northwind Traders        47
Name: count, dtype: int64

Color
Black          602
White          505
Silver         417
Grey           283
Blue           200
Red             99
Pink            84
Brown           77
Green           74
Orange          55
Gold            50
Yellow          36
Azure           14
Silver Grey     14
Purple           6
Transparent      1
Name: count, dtype: int64

Unit Cost USD
$15.29      34
$210.72     29
$321.44     29
$52.00      28
$152.94     27
            ..
$293.39      1
$255.68      1
$13.26       1
$285.12      1
$211.05      1
Name: count, Length: 480, dtype: int64

Unit Price USD
$29.99        30
$635.99       29
$699.00       29
$299.00       28
$129.00       28
              ..
$460.00        1
$1,030.00      1
$988.00        1
$1,099.00      1
$967.00        1
Name: count, Length: 426, dtype: int64

SubcategoryKey
308    201
806    158
702    120
305    103
405    103
803    102
504    101
306    101
402    100
401    100
203    100
501     92
602     90
802     86
304     78
301     78
808     78
805     74
801     70
406     69
807     62
503     62
201     50
106     50
205     46
701     46
101     45
303     45
804     31
505     30
202     26
104     20
Name: count, dtype: int64

Subcategory
Computers Accessories               201
Lamps                               158
Download Games                      120
Projectors & Screens                103
Camcorders                          103
Microwaves                          102
Smart phones & PDAs                 101
Printers, Scanners & Fax            101
Digital SLR Cameras                 100
Digital Cameras                     100
Home Theater System                 100
Home & Office Phones                 92
Movie DVD                            90
Refrigerators                        86
Monitors                             78
Laptops                              78
Fans                                 78
Coffee Machines                      74
Washers & Dryers                     70
Cameras & Camcorders Accessories     69
Air Conditioners                     62
Touch Screen Phones                  62
Televisions                          50
Bluetooth Headphones                 50
Car Video                            46
Boxed Games                          46
MP4&MP3                              45
Desktops                             45
Water Heaters                        31
Cell phones Accessories              30
VCD & DVD                            26
Recording Pen                        20
Name: count, dtype: int64

CategoryKey
8    661
3    606
4    372
5    285
2    222
7    166
1    115
6     90
Name: count, dtype: int64

Category
Home Appliances                  661
Computers                        606
Cameras and camcorders           372
Cell phones                      285
TV and Video                     222
Games and Toys                   166
Audio                            115
Music, Movies and Audio Books     90
Name: count, dtype: int64

In [89]:
print('\nNull values Prod Table:\n', df_prod.isnull().sum())

Null values Prod Table:
 ProductKey        0
Product Name      0
Brand             0
Color             0
Unit Cost USD     0
Unit Price USD    0
SubcategoryKey    0
Subcategory       0
CategoryKey       0
Category          0
dtype: int64

In [90]:
for i in df_sales.columns:
  print(df_sales[i].value_counts(),'\n')

Order Number
1025000    7
1529001    7
1529028    7
1220005    7
1422011    7
          ..
1469018    1
786002     1
1761001    1
786001     1
366000     1
Name: count, Length: 26326, dtype: int64

Line Item
1    26326
2    16789
3    10248
4     5125
5     2175
6     1476
7      745
Name: count, dtype: int64

Order Date
12/21/2019    222
1/4/2020      219
12/28/2019    215
12/29/2018    206
2/22/2020     204
             ...
6/11/2017       1
7/8/2018        1
3/17/2019       1
8/19/2018       1
10/16/2016      1
Name: count, Length: 1641, dtype: int64

Delivery Date
1/6/2020      50
1/7/2019      44
12/25/2019    43
2/24/2019     41
1/5/2020      41
              ..
10/27/2020     1
5/17/2017      1
10/29/2020     1
5/9/2017       1
8/25/2020      1
Name: count, Length: 1492, dtype: int64

CustomerKey
723572     36
1579183    32
1925694    32
1942072    29
1972249    29
           ..
974784      1
1068351     1
315725      1
1520217     1
1237927     1
Name: count, Length: 11887, dtype: int64

StoreKey
0     13165
9      1577
50     1519
55     1518
54     1498
61     1485
59     1472
45     1471
57     1442
44     1436
65     1395
8      1360
51     1356
64     1353
47     1348
43     1340
66     1295
48     1289
56     1287
53     1284
10     1269
39     1054
40     1050
36     1049
49     1041
38     1034
42     1017
29     1011
37      995
30      976
63      948
5       892
22      800
62      778
27      721
24      703
23      674
19      635
6       615
33      498
32      454
34      448
41      444
20      443
4       431
31      417
21      391
26      295
1       292
15      235
12      224
16      214
28      214
17      210
18      194
13      184
14      126
2        18
Name: count, dtype: int64

ProductKey
423     162
446     158
434     158
458     158
448     157
       ...
2306      1
2346      1
2232      1
2243      1
193       1
Name: count, Length: 2492, dtype: int64

Quantity
1     18311
2     13611
3     10907
4      5441
6      3699
7      3639
5      3619
8      1849
10      913
9       895
Name: count, dtype: int64

Currency Code
USD    33767
EUR    12621
GBP     8140
CAD     5415
AUD     2941
Name: count, dtype: int64

In [91]:
print('\nNull values Sales Table:\n', df_sales.isnull().sum())

Null values Sales Table:
 Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64

In [92]:
df_sales.groupby('Order Number').filter(lambda x: len(x) > 1)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD
5,366002,3,1/1/2016,1/12/2016,266019,0,1080,4,CAD
...,...,...,...,...,...,...,...,...,...
62877,2243029,5,2/20/2021,2/27/2021,887764,0,1449,4,EUR
62878,2243029,6,2/20/2021,2/27/2021,887764,0,1456,2,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [93]:
df_sales=df_sales[~df_sales.duplicated()]
df_sales

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD
...,...,...,...,...,...,...,...,...,...
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [94]:
df_sales.fillna('Unknown', inplace=True)
df_sales

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,Unknown,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD
...,...,...,...,...,...,...,...,...,...
62879,2243030,1,2/20/2021,Unknown,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [95]:
df_sales.isnull().sum()

Order Number     0
Line Item        0
Order Date       0
Delivery Date    0
CustomerKey      0
StoreKey         0
ProductKey       0
Quantity         0
Currency Code    0
dtype: int64

In [98]:
merged_df=pd.merge(df_cus,df_sales,on='CustomerKey', how='left')
merged_df.astype('int64')

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday,Order Number,Line Item,Order Date,Delivery Date,StoreKey,ProductKey,Quantity,Currency Code
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939,1776007.0,1.0,11/11/2019,11/13/2019,0.0,53.0,2.0,AUD
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979,1109001.0,1.0,1/13/2018,Unknown,6.0,443.0,4.0,AUD
2,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979,1109001.0,2.0,1/13/2018,Unknown,6.0,656.0,4.0,AUD
3,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979,1109001.0,3.0,1/13/2018,Unknown,6.0,1084.0,3.0,AUD
4,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979,1781006.0,1.0,11/16/2019,Unknown,6.0,418.0,3.0,AUD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66258,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965,1269016.0,2.0,6/22/2018,Unknown,56.0,425.0,5.0,USD
66259,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965,1269016.0,3.0,6/22/2018,Unknown,56.0,344.0,7.0,USD
66260,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965,1269016.0,4.0,6/22/2018,Unknown,56.0,1162.0,1.0,USD
66261,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965,1872055.0,1.0,2/15/2020,Unknown,53.0,434.0,10.0,USD
66262,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965,1872055.0,2.0,2/15/2020,Unknown,53.0,1721.0,3.0,USD